# Dependabot configuration file for keeping dependencies up-to-date
version: 2
updates:
  - package-ecosystem: "npm" # ğŸ› ï¸ Node.js package ecosystem
    directory: "/" # ğŸ“ Location of package manifests
    schedule:
      interval: "weekly" # â° Frequency of updates
    allow:
      - dependency-type: "all" # ğŸ‘¥ Update all types of dependencies (direct and development)

  - package-ecosystem: "gomod" # ğŸ  Hugo and Go modules
    directory: "/" # ğŸ“ Location of Go module manifests (for Hugo)
    schedule:
      interval: "weekly" # â° Frequency of updates
    allow:
      - dependency-type: "all" # ğŸ‘¥ Update all types of dependencies (direct and indirect)
