# Dependency Review Action ğŸ”
#
# This Action will scan dependency manifest files that change as part of a Pull Request,
# surfacing known-vulnerable versions of the packages declared or updated in the PR.
# Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable
# packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: 'Dependency Review ğŸ”'
on:
  pull_request:
    branches: [ "main" ] # ğŸ  Target branch for PRs

# If using a dependency submission action in this workflow this permission will need to be set to:
#
# permissions:
#   contents: write
#
# https://docs.github.com/en/enterprise-cloud@latest/code-security/supply-chain-security/understanding-your-software-supply-chain/using-the-dependency-submission-api
permissions:
  contents: read # ğŸ“¦ Read access to repository contents
  # Write permissions for pull-requests are required for using the `comment-summary-in-pr` option, comment out if you aren't using this option
  pull-requests: write # âœï¸ Write access to pull requests

jobs:
  dependency-review:
    runs-on: ubuntu-latest # ğŸ–¥ï¸ Runner environment
    steps:
      - name: 'Checkout Repository ğŸš€'
        uses: actions/checkout@v4 # ğŸ”„ Checkout code
      - name: 'Dependency Review ğŸ›¡ï¸'
        uses: actions/dependency-review-action@v4 # ğŸ” Review dependencies
        # Commonly enabled options, see https://github.com/actions/dependency-review-action#configuration-options for all available options.
        with:
          comment-summary-in-pr: always # ğŸ’¬ Comment on PRs with a summary
        #   fail-on-severity: moderate # âš ï¸ Fail on moderate or higher severity issues
        #   deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later # ğŸš« Deny specific licenses
